#!/bin/sh
set -e
trap exit TERM INT

echo "info: starting"

if [ -z "$TENANT" ] ; then
	echo "[ERRO] missing TENANT env variable"
	exit 1
fi

if [ -z "$FIO_TOKEN" ] ; then
	echo "error: missing FIO_TOKEN env variable"
	exit 1
fi

cd /opt/fio-bco && \
	dumb-init node app.js ${TENANT} ${FIO_TOKEN}
