version: '2'

services:

  cron:
    image: openbank/fio-bco
    restart: "no"
    tty: true
    environment:
      - TENANT
      - FIO_TOKEN
    volumes:
      - ./data-real:/data
      - ./config:/opt/fio-bco/config:ro
    depends_on:
      - server
      - queue
      - vault

  server:
    image: openbank/server
    restart: unless-stopped
    environment:
      - PERSISTENCE_PATH=/data
    volumes:
      - ./data-real:/data
    ports:
      - "8080"

  queue:
    image: openbank/lake
    restart: "no"
    ports:
      - "5562"
      - "5561"
    command: ["run"]

  vault:
    image: openbank/vault
    restart: unless-stopped
    environment:
      - TENANT
      - PERSISTENCE_PATH=/data
    volumes:
      - ./data-real:/data
