version: '2'

services:

  cron:
    image: openbank/fio-bco:latest
    restart: unless-stopped
    tty: true
    environment:
      - TENANT=FIO
      - FIO_TOKEN=${FIO_TOKEN}
    volumes:
      - ./data-real:/data
      - ./config:/opt/fio-bco/config:ro
    depends_on:
      - server
      - queue
      - vault

  server:
    image: openbank/server:latest
    restart: unless-stopped
    environment:
      - PERSISTENCE_PATH=/data
    volumes:
      - ./data-real:/data
    ports:
      - "8080"

  queue:
    image: openbank/queue:latest
    restart: unless-stopped
    ports:
      - "5562"
      - "5561"

  vault:
    image: openbank/vault:latest
    restart: unless-stopped
    environment:
      - TENANT=FIO
      - PERSISTENCE_PATH=/data
    volumes:
      - ./data-real:/data
