#!/bin/sh

set -e

delete_service_files() {
  if [ -f "/lib/systemd/system/fio-bco-rest.service" ] ; then
    rm /lib/systemd/system/fio-bco-rest.service
  fi

  if [ -f "/lib/systemd/system/fio-bco-import@.service" ] ; then
    rm /lib/systemd/system/fio-bco-import@.service
  fi

  if [ -f "/lib/systemd/system/fio-bco.service" ] ; then
    rm /lib/systemd/system/fio-bco.service
  fi

  if [ -f "/lib/systemd/system/fio-bco.path" ] ; then
    rm /lib/systemd/system/fio-bco.path
  fi
}

delete_displace_files() {
  if [ -f "/etc/init/fio-bco.conf" ] ; then
    rm /etc/init/fio-bco.conf
  fi
}

case "$1" in

  purge)
    # userdel openbank || :

    delete_service_files
    delete_displace_files

    (systemctl daemon-reload || :)
    (systemctl reset-failed || :)
  ;;

  remove)
    (systemctl -a -t service --no-legend  | awk '$1 ~ /fio-bco/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
    (systemctl daemon-reload || :)

    delete_displace_files
  ;;

  upgrade|deconfigure)
    systemctl stop fio-bco 2> /dev/null || :
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
