#!/bin/sh

set -e

case "$1" in

  install|upgrade)

    if [ ! -f "/etc/init/fio-bco.conf" ] ; then
      mkdir -p /etc/init
      touch /etc/init/fio-bco.conf

      echo "FIO_BCO_STORAGE=/data" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_LOG_LEVEL=INFO" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_METRICS_REFRESHRATE=1s" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_FIO_GATEWAY=https://www.fio.cz" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_SYNC_RATE=22s" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_LEDGER_GATEWAY=https://127.0.0.1:4401" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_VAULT_GATEWAY=https://127.0.0.1:4400" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_METRICS_OUTPUT=/opt/fio-bco/metrics/metrics.json" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_LAKE_HOSTNAME=127.0.0.1" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_HTTP_PORT=4002" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_SECRETS=/opt/fio-bco/secrets" >> /etc/init/fio-bco.conf
      echo "FIO_BCO_ENCRYPTION_KEY=/opt/fio-bco/secrets/fs_encryption.key" >> /etc/init/fio-bco.conf
    fi

    secrets=$(sed -n -e 's/^.*FIO_BCO_SECRETS=//p' /etc/init/fio-bco.conf 2>/dev/null | awk '{gsub(/^ +| +$/,"")} {print $0}')

    if [ -z "${secrets}" ] ; then
      (>&2 echo "FIO_BCO_SECRETS are not defined at /etc/init/fio-bco.conf")
      exit 1
    fi

    if [ ! -f "${secrets}/domain.local.crt" ] || [ ! -f "${secrets}/domain.local.key" ] ; then
      mkdir -p "${secrets}"

      openssl req \
        -x509 \
        -nodes \
        -newkey rsa:2048 \
        -keyout "${secrets}/domain.local.key" \
        -out "${secrets}/domain.local.crt" \
        -days 1 \
        -subj "/C=CZ/ST=Czechia/L=Prague/O=OpenBanking/OU=IT/CN=localhost/emailAddress=jan.cajthaml@gmail.com"
      echo "generated temporary certificates at ${secrets} valid for 24 hours"
    fi

    encryptionKey=$(sed -n -e 's/^.*FIO_BCO_ENCRYPTION_KEY=//p' /etc/init/fio-bco.conf 2>/dev/null | awk '{gsub(/^ +| +$/,"")} {print $0}')

    if [ -z "${encryptionKey}" ] ; then
      (>&2 echo "FIO_BCO_ENCRYPTION_KEY is not defined at /etc/init/fio-bco.conf")
      exit 1
    fi

    if [ ! -f "${encryptionKey}" ] ; then
      mkdir -p $(basename "${encryptionKey}")
      openssl rand -hex 32 | xargs --no-run-if-empty echo -n > "${encryptionKey}"
      echo "generated 32B encryption key at ${encryptionKey}"
    fi

  ;;

  abort-upgrade)
  ;;

  *)
    (>&2 echo "preinst called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
