required = [
  "github.com/pebbe/zmq4",
  "github.com/gin-gonic/gin"
]

[prune]
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/pebbe/zmq4"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/gin"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/jancajthaml-openbank/actor-system"
