.nh
.TH "FIO-BCO-REST" "1" "Jul 2020" "FioBank Manager" "OpenBank FioBank Manager REST Server Manual"
.sp
.SH "NAME"
lake \- starts openbank fio bank connector REST server
.SH "SYNOPSIS"
.sp
.nf
\fIfio-bco-rest
.fi
.sp
.SH "DESCRIPTION"
.sp
The fio bco rest provides REST server for accessing and manipulating fio bco units
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
