.nh
.TH "FIO-BCO-IMPORT" "1" "Jul 2020" "FioBank Import" "OpenBank FioBank Import Manual"
.sp
.SH "NAME"
lake \- starts openbank account vault account unit
.SH "SYNOPSIS"
.sp
.nf
\fIfio-bco-import
.fi
.sp
.SH "DESCRIPTION"
.sp
The fio bco import manages tenant fio tokens and imports transactions from fio bank
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
